app/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('author/<int:pk>/', views.list_posts_by_author, name='posts-by-author'),
    path('category/<str:name>/', views.list_posts_by_category, name='posts-by-category'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', views.post_detail_view, name='post-detail'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('image/', views.ImageListView.as_view(), name='image-list'),
    path('image/new/', views.ImageCreateView.as_view(), name='image-create'),
    path('image/<slug:slug>/', views.ImageDetailView.as_view(), name='image-detail'),
    path('image/<slug:slug>/update/', views.ImageUpdateView.as_view(), name='image-update'),
    path('image/<slug:slug>/delete/', views.ImageDeleteView.as_view(), name='image-delete'),
]

app/ni_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('blog.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', next_page='blog:home'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.update_user_and_profile, name='profile'),
    path('register/', views.register, name='register'),
]

app/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=128)
    intro = models.TextField()
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Image(models.Model):
    name = models.CharField(max_length=64, unique=True)
    slug = models.SlugField(max_length=64, unique=True, null=True)
    image = models.ImageField(upload_to='post_pics/%Y-%m-%d')
    date = models.DateTimeField(default=timezone.now)
    is_header = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('blog:image-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

app/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.utils.text import slugify

from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.models import User
from .models import Post, Category, Image


def home(request):
    posts = Post.objects.order_by('-date')
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/home.html', context={'page_obj': page_obj})


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def list_posts_by_author(request, pk):
    user = get_object_or_404(User, pk=pk)
    posts = Post.objects.filter(author=user).order_by('-date')
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': user
    }
    return render(request, 'blog/posts_filtered.html', context=context)


def list_posts_by_category(request, name):
    category = get_object_or_404(Category, name=name)
    posts = Post.objects.filter(category=category).order_by('-date')
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'category': category
    }
    return render(request, 'blog/posts_filtered.html', context=context)


def post_detail_view(request, pk):
    post = Post.objects.get(pk=pk)
    images = Image.objects.filter(post=post)
    context = {
        'object': post,
        'images': images
    }
    return render(request, template_name='blog/post_detail.html', context=context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'intro', 'content', 'category']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'intro', 'content', 'category']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class ImageCreateView(LoginRequiredMixin, CreateView):
    model = Image
    fields = ['name', 'image', 'is_header', 'post']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.slug = slugify(form.instance.name)
        return super().form_valid(form)


class ImageDetailView(DetailView):
    model = Image


class ImageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Image
    success_url = reverse_lazy('blog:image-list')
    fields = ['name', 'image', 'is_header', 'post']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        image = self.get_object()
        if self.request.user == image.owner:
            return True
        return False


class ImageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Image
    success_url = reverse_lazy('blog:image-list')

    def test_func(self):
        image = self.get_object()
        if self.request.user == image.owner:
            return True
        return False


class ImageListView(LoginRequiredMixin, ListView):
    model = Image
    paginate_by = 10

app/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <p>It is a web app that is used to manage web blog page.<br>Developed using Django, HTML, CSS. Deployed on AWS using docker, docker-compose.</p>
{% endblock content %}

app/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'blog/main.css' %}" type="text/css">

    {% if title %}
        <title>thBlog - {{ title }}</title>
    {% else %}
        <title>thBlog</title>
    {% endif %}

</head>

<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href=" {% url 'blog:home' %} ">thBlog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href=" {% url 'blog:home' %} ">Home</a>
              <a class="nav-item nav-link" href=" {% url 'blog:about' %} ">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href=" {% url 'blog:post-create' %} ">New post</a>
                    <a class="nav-item nav-link" href=" {% url 'blog:image-list' %} ">Images</a>
                    <a class="nav-item nav-link" href=" {% url 'users:profile' %} ">Profile</a>
                    <a class="nav-item nav-link" href=" {% url 'logout' %} ">Logout</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>

            <div class="col-md-4">
                <div class="content-section">
                    <h3>Categories:</h3>
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light"><a href="{% url 'blog:posts-by-category' name='Travel' %}">Travel</a></li>
                            <li class="list-group-item list-group-item-light"><a href="{% url 'blog:posts-by-category' name='Food' %}">Food</a></li>
                            <li class="list-group-item list-group-item-light"><a href="{% url 'blog:posts-by-category' name='Coding' %}">Coding</a></li>
                            <li class="list-group-item list-group-item-light"><a href="{% url 'blog:posts-by-category' name='Interior design' %}">Interior design</a></li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

app/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
    {% block filtered %}{% endblock filtered %}
    <!--post list view-->
        {% for post in page_obj %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{% url 'blog:posts-by-category' post.category.name %}">{{ post.category }}</a>
                        <a class="mr-2" href="{% url 'blog:posts-by-author' post.author.pk %}">{{ post.author }}</a>
                        <small class="text-muted">{{ post.date|date:'F d, Y' }}</small>
                    </div>
                    <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.intro }}</p>
                </div>
            </article>
        {% endfor %}
    <!--end post list view-->

    <!--pagination-->
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">back</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    <!--end pagination-->

{% endblock content %}

app/blog/templates/blog/image_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete image</legend>
                <h2>Are you sure you want to delete the image: {{ object.name }} ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:image-detail' object.slug %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

app/blog/templates/blog/image_detail.html
{% extends 'blog/base.html' %}

{% block content %}

    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:post-detail' object.post.pk ">{{ object.post }}</a>
          <small class="text-muted">{{ object.date|date:'F d, Y' }}</small>
          <small class="text-muted">{{ object.owner }}</small>
            <div>
                {% if object.owner == user %}
                    <a class='btn btn-secondary btn-sm mt-1 mb-1' href="{% url 'blog:image-update' object.slug %}">Edit</a>
                    <a class='btn btn-danger btn-sm mt-1 mb-1' href="{% url 'blog:image-delete' object.slug %}">Delete</a>
                {% endif %}
            </div>
        </div>
        <h2 class="article-title">{{ object.name }}</h2>
        <img src="{{ object.image.url }}" height='500' width='700'>
      </div>
    </article>

{% endblock content %}

app/blog/templates/blog/image_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add new image</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add</button>
            </div>
        </form>
    </div>
{% endblock content %}

app/blog/templates/blog/image_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <a class='btn btn-secondary btn-sm mt-1 mb-1' href="{% url 'blog:image-create' %}">Add new</a>
    <h1 class="mb-3">Images in the library:</h1>
    <!--ImageListView-->
        {% for image in page_obj %}
            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <small class="text-muted">{{ image.post }} |</small>
                        <small class="text-muted">{{ image.owner }} |</small>
                        <small class="text-muted">{{ image.date|date:'F d, Y' }}</small>
                    </div>
                    <h2><a class="article-title" href="{% url 'blog:image-detail' image.slug %}">{{ image.name }}</a></h2>
                    <img class="account-img" src="{{ image.image.url }}">
                </div>
            </article>
        {% endfor %}
    <!--end ImageListView-->

    <!--pagination-->
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">back</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    <!--end pagination-->

{% endblock content %}

app/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete post</legend>
                <h2 >Are you sure you want to delete the post: {{ object.title }} ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

app/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:posts-by-category' object.category.name %}">{{ object.category }}</a>
          <a class="mr-2" href="{% url 'blog:posts-by-author' object.author.pk %}">{{ object.author }}</a>
          <small class="text-muted">{{ object.date|date:'F d, Y' }}</small>
            <div>
                {% if object.author == user %}
                    <a class='btn btn-secondary btn-sm mt-1 mb-1' href="{% url 'blog:post-update' object.id %}">Edit</a>
                    <a class='btn btn-danger btn-sm mt-1 mb-1' href="{% url 'blog:post-delete' object.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.intro }}</p>
        <p class="article-content">{{ object.content }}</p>

          {% for image in images %}
          <img src="{{ image.image.url }}" height="500" width="700">
          {% endfor %}

      </div>
    </article>

{% endblock content %}

app/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add</button>
            </div>
        </form>
    </div>
{% endblock content %}

app/blog/templates/blog/posts_filtered.html
{% extends 'blog/home.html' %}

{% block filtered %}
    {% if author %}
        <h1 class="mb-3">Author: {{ author }}</h1>
    {% elif category %}
        <h1 class="mb-3">Category: {{ category }}</h1>
    {% endif %}
{% endblock filtered %}